dictionary={
    "deed":"eylem",
    "scarce":"seyrek,kıt",
    "breed":"yavrulamak",
    "boundary":"sınır",
    "ease":"kolaylaştırmak",
    "substance":"madde,cisim",
    "presumably":"tahminen",
    "vast":"extremly big",
    "facilitate":"olanak tanımak",
    "compromise":"anlaşmaya varmak",
    "deficit":"açık(mali)",
    "devote":"adamak",
    "appendix":"ek",
    "seize":"el koymak",
    "fierce":"vahşet,vahşi",
    "grease":"yağ(hayvan,sebze)",
    "implication":"bir kişiyi olumsuz bir şeye karıştırma",
    "tackle":"ele almak",
    "indifferent":"umursamaz",
    "constrain":"baskı yapmak,kısıtlamak",
    "flood":"sel",
    "pile":"yığın",
    "prohibit":"yasaklamak,önlemek",
    "shortage":"kıtlık",
    "obedience":"bağlılık",
    "outwards":"dışa doğru",
    "bundle":"demet",
    "premises":"mülk",
    "correlation":"karşılıklı ilişki",
    "invade":"işgal etmek",
    "foresee":"öngörmek",
    "Idle":"boş durmak",
    ######################
    "outlook":"the likely future situation",
    "despair":"umudunu kesmek",
    "settle":"yerleşmek",
    "drawer":"çekmece",
    "tempt":"baştan çıkarmak",
    "limb":"bacak",
    "reassure":"güvence vermek",
    "crack":"yarılmak,çatlamak",
    "hip":"kalça",
    "dove":"güvercin",
    "foster":"teşvik etmek",
    "hay":"saman",
    "grain":"tahıl",
    "engage":"to be doing or to become involved in an activity/işe almak",
    "reluctant":"isteksiz",
    "humble":"mütevazı",
    "rigid":"sert,sabit",
    "powder":"toz",
    "virtue":"erdem",
    "entitle":"hak kazandırmak",
    "imprison":"hapse atmak",
    "exceed":"sınırı aşmak",
    "plug":"tıpa",
    ########################
    "hollow":"oyuk",
    "pan":"tava",
    "bribe":"rüşvet",
    "relief":"rahatlama",
    "stiff":"katı",
    "cultivate":"ekip biçmek",
    "dialect":"lehçe,ağız",
    "stir":"karıştırmak",
    "utilize":"faydalı hale getirmek",
    "plough":"sabanla sürmek",
    "pinch":"çimdiklemek",
    "splendid":"müthiş",
    "scope":"faaliyet alanı",
    "neat":"düzenli",
    "spill":"dökmek(çarpıp)",
    "edge":"köşe,uç",
    "sue":"dava açmak",
    "superior":"üstün",
    "executive":"yönetici",
    "deceive":"aldatmak",
    "ditch":"hendek",
    "vague":"şüpheli",
    "comprise":"kapsamak",
    "thereby":"böylece,o sebeple",
    "nerve":"sinir",
    "feast":"ziyafet",
    "pretend":"yapar gibi görünmek",
    "midst":"ortasında",
    "spit":"tükürmek",


}
